<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Switcher.Contracts\Switcher.Contracts.csproj" />
    <ProjectReference Include="..\Switcher.Engine\Switcher.Engine.csproj" />
    <ProjectReference Include="..\Switcher.Web\Switcher.Web.csproj" />
    <ProjectReference Include="..\Switcher.Atem\Switcher.Atem.csproj" />
    <ProjectReference Include="..\Switcher.Hid\Switcher.Hid.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
